# Generated by Django 2.1.4 on 2019-01-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_auto_20190102_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=100)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('reason', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'Request',
            },
        ),
    ]
