# Generated by Django 2.1.4 on 2019-01-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_requestinventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinventory',
            name='endDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='requestinventory',
            name='startDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
