# Generated by Django 2.1.4 on 2019-01-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_requestinventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinventory',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
