# Generated by Django 2.1.4 on 2019-01-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_requestinventory_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinventory',
            name='Request_id',
            field=models.CharField(max_length=100),
        ),
    ]
