# Generated by Django 2.1.4 on 2019-01-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0014_auto_20190107_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestinventory',
            name='Request_id',
        ),
        migrations.AddField(
            model_name='requestinventory',
            name='request_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
