# Generated by Django 2.1.4 on 2019-01-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0015_auto_20190107_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinventory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
