# Generated by Django 2.1.4 on 2019-01-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0016_auto_20190107_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinventory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
