# Generated by Django 2.1.4 on 2019-01-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0017_auto_20190107_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinventory',
            name='endDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='requestinventory',
            name='startDate',
            field=models.DateTimeField(),
        ),
    ]
