# Generated by Django 2.1.4 on 2019-01-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0019_auto_20190107_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='must_change_password',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_first_login',
            field=models.BooleanField(default=True),
        ),
    ]
