# Generated by Django 2.1.4 on 2019-01-12 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0021_auto_20190112_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='designation',
        ),
    ]
