# Generated by Django 2.1.4 on 2019-01-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0023_auto_20190121_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Hierarchy',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Employee_id', models.CharField(max_length=200)),
                ('supervisor_1', models.CharField(max_length=100)),
                ('supervisor_2', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'User_Hierarchy',
            },
        ),
        migrations.AlterModelTable(
            name='designations',
            table='User_Roles',
        ),
        migrations.AlterModelTable(
            name='status',
            table='Request_Status',
        ),
    ]
