# Generated by Django 2.1.4 on 2019-01-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0024_auto_20190121_1507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Hierarchy',
            new_name='UserHierarchy',
        ),
    ]
