# Generated by Django 2.1.4 on 2019-01-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0025_auto_20190121_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinventory',
            name='comment',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
