# Generated by Django 2.1.4 on 2019-01-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0026_requestinventory_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Designations',
        ),
    ]
