# Generated by Django 2.1.4 on 2019-01-23 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0028_remove_roles_level'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='roles',
            table='Roles',
        ),
    ]
