# Generated by Django 2.1.4 on 2019-01-28 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0029_auto_20190123_2144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='status_type',
            new_name='status_code',
        ),
    ]
