# Generated by Django 2.1.4 on 2019-01-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0030_auto_20190128_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.IntegerField()),
                ('model', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100)),
                ('sim_no', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('configuration', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Inventory_Values',
            },
        ),
    ]
