# Generated by Django 2.1.4 on 2019-01-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0031_inventoryvalues'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryvalues',
            name='manufacturer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryvalues',
            name='configuration',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
