# Generated by Django 2.1.4 on 2019-01-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0032_auto_20190130_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='inventoryvalues',
            name='product_type',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='inventoryvalues',
            name='sim_no',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
