# Generated by Django 2.1.4 on 2019-01-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0034_auto_20190130_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryvalues',
            name='AssignedTo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
